config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/search', to: 'polies#index'
  get '/polies', to: 'polies#index'
  get '/polies/new', to: 'polies#new'

  resources :polies
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/poly.rb
class Poly < ApplicationRecord

  def self.search(search)
    where("name ILIKE ? OR description ILIKE ?", "%#{search}%", "%#{search}%")
  end

  #make sure the description can only be 140 characters
  validates :description, length: { maximum: 140 }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/polies_controller.rb
class PoliesController < ApplicationController
  before_action :set_poly, only: [:show, :edit, :update, :destroy]

  # GET /polies
  # GET /polies.json
  def index
    @polies = Poly.all
    if params[:search]
      @polies = Poly.search(params[:search]).order("created_at DESC")
    else
      @polies = Poly.all.order("created_at DESC")
    end
  end

  # GET /polies/1
  # GET /polies/1.json
  def show
  end

  # GET /polies/new
  def new
    @poly = Poly.new
  end

  # GET /polies/1/edit
  def edit
  end

  # POST /polies
  # POST /polies.json
  def create
    @poly = Poly.new(poly_params)

    respond_to do |format|
      if @poly.save
        format.html { redirect_to @poly, notice: 'Poly was successfully created.' }
        format.json { render :show, status: :created, location: @poly }
      else
        format.html { render :new }
        format.json { render json: @poly.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polies/1
  # PATCH/PUT /polies/1.json
  def update
    respond_to do |format|
      if @poly.update(poly_params)
        format.html { redirect_to @poly, notice: 'Poly was successfully updated.' }
        format.json { render :show, status: :ok, location: @poly }
      else
        format.html { render :edit }
        format.json { render json: @poly.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polies/1
  # DELETE /polies/1.json
  def destroy
    @poly.destroy
    respond_to do |format|
      format.html { redirect_to polies_url, notice: 'Poly was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poly
      @poly = Poly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poly_params
      params.require(:poly).permit(:name, :description, :docs, :bugtracker, :downloads, :license, :author, :submittedby, :website, :gitsshurl, :repotype)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polies_helper.rb
module PoliesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The Poly - By Chris Figueroa
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top ">
  <div class="container">
    <%= link_to image_tag("gpmlogo.png", height: '32', width: '32'), home_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "View All Poly's", polies_path %></li>
        <li><%= link_to "Create Poly", polies_new_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Poly</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <!-- <%= render 'layouts/footer' %> -->
    </div>
  </body>
</html>

app/views/polies/_form.html.erb
<%= form_for(poly) do |f| %>
  <% if poly.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(poly.errors.count, "error") %> prohibited this poly from being saved:</h2>

      <ul>
      <% poly.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Name: The name users will search for" %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description, "Description: What is this poly? Maximum 140 Characters" %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :docs, "Documentation URL: (Optional)" %>
    <%= f.url_field :docs %>
  </div>

  <div class="field">
    <%= f.label :bugtracker, "Bug Tracker: Example - Github Issues URL (Optional)" %>
    <%= f.url_field :bugtracker %>
  </div>

  <div class="field">
    <%= f.label :license, "License: (Optional)" %>
    <%= f.text_field :license %>
  </div>

  <div class="field">
    <%= f.label :author, "Author: " %>
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :submittedby, "Submitted By: " %>
    <%= f.text_field :submittedby %>
  </div>

  <div class="field">
    <%= f.label :website, "Website: " %>
    <%= f.url_field :website %>
  </div>

  <div class="field">
    <%= f.label :gitsshurl, "HTTPS URL: Example - https://github.com/kinifi/poly-server.git (Optional)" %>
    <%= f.text_field :gitsshurl %>
  </div>

  <div class="field">
    <%= f.label :repotype, "Repo Type: git, mercurial, svn, download" %>
    <%= f.text_field :repotype %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/polies/edit.html.erb
<h1>Editing Poly</h1>

<%= render 'form', poly: @poly %>

<%= link_to 'Show', @poly %> |
<%= link_to 'Back', polies_path %>

app/views/polies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Poly's</h1>
<br>
<hr>

<table id="polytable">
  <tbody>
    <% @polies.each do |poly| %>
      <tr>
        <td id="websitetitle" colspan="2"><%= poly.name %></td>
      </tr>
      <br>
      <tr>
        <td id="website"><%= poly.description %></td>
        <!-- <td><%= poly.docs %></td>
        <td><%= poly.bugtracker %></td> -->
        <!-- <td><%= poly.downloads %></td> -->
        <!-- <td><%= poly.license %></td>
        <td><%= poly.author %></td>
        <td><%= poly.submittedby %></td> -->
        <!-- <td id="website"><%= poly.website %></td> -->
        <!-- <td><%= poly.gitsshurl %></td>
        <td><%= poly.repotype %></td> -->
        <td id="website"><%= link_to 'Show Info', poly %></td>
        <!-- <td><%= link_to 'Edit', edit_poly_path(poly) %></td> -->
        <!-- <td><%= link_to 'Destroy', poly, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- <%= link_to 'Create New Poly', new_poly_path %> -->

app/views/polies/new.html.erb
<h1>Create A New Poly</h1>
<p> Please fill out all the information below. </p>
<%= render 'form', poly: @poly %>

<%= link_to 'Cancel', polies_path %>

app/views/polies/show.html.erb
<p id="notice"><%= notice %></p>

<br>
<h1>
  <%= @poly.name %>
</h1>
<hr>

<h5>
  <%= @poly.description %>
</h5>
<hr>

<!-- <p>
  <strong>Downloads:</strong>
  <%= @poly.downloads %>
</p> -->

<p>
  <strong>Website:</strong>
  <%= link_to @poly.website, @poly.website %>
</p>

<p>
  <strong>Bugtracker:</strong>
  <%= link_to @poly.bugtracker, @poly.bugtracker %>
</p>

<p>
  <strong>Docs:</strong>
  <%= link_to @poly.docs, @poly.docs %>
</p>

<p>
  <strong>License:</strong>
  <%= @poly.license %>
</p>

<p>
  <strong>Author:</strong>
  <%= @poly.author %>
</p>

<p>
  <strong>Submitted By:</strong>
  <%= @poly.submittedby %>
</p>
<hr>

<p>
  <strong>Repotype:</strong>
  <%= @poly.repotype %>
</p>

<p>
  <strong>HTTPS URL:</strong>
  <%= @poly.gitsshurl %>
</p>

<hr>

<p>Note: If a Poly needs to be deleted please contact @kinifi</p>
<%= link_to 'Edit', edit_poly_path(@poly) %> |
<%= link_to 'Back To List', polies_path %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<div class="home__image-wrap">
  <div class="center jumbotron">
    <br>
    <h1>Poly</h1>
    <%= image_tag("gpmlogo.png", height: '128', width: '128') %>
    <h2>Find, Install, and Create Your Own Poly's</h2>
    <h5>Poly is a engine agnostic library of code snippets, editors, full tools and more! In one location for game devs.</h5>
    <br>

    <%= form_tag('/search', :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Ex: Unity, Gamemaker" %>
        <%= submit_tag "Search", :name => nil %>
      <% end %>
    </div>
  </div>